name: "Create myfile.txt"
description: "Action to create myfile.txt in specified directories"
inputs:
  directory:
    description: "Directory to create myfile.txt in"
    required: true
runs:
  using: "composite"
  steps:
    - name: Create myfile.txt
      shell: bash
      run: |
        # Loop through each item in the array and print it
        for dir in ${{ inputs.directory }}; do
          echo "Processing directory: $dir"
          # Add your logic here to create myfile.txt in each directory
        done
