name: "Create myfile.txt"
description: "Action to create myfile.txt in specified directories"
inputs:
  directory:
    description: "Directory to create myfile.txt in"
    required: true
runs:
  using: "composite"
  steps:
    - name: Create myfile.txt
      shell: bash
      run: |
        # Parse the input argument
        DIRECTORY=$1
        # Loop through each item in the array and recursively print folder names
        for dir in "${DIRECTORY[@]}"; do
          echo "Processing directory: $dir"
          find "$dir" -type d -exec basename {} \; # Prints folder names recursively
        done
