name: "Create myfile.txt"
description: "Action to create myfile.txt in specified directories"
inputs:
  directory:
    description: "Directory to create myfile.txt in"
    required: true
runs:
  using: "composite"
  steps:
    - name: Create myfile.txt
      shell: bash
      run: |
        const folder = getInput('directory');
        echo ${folder};
