---
name: Create myfile.txt in each second-level subfolder

on:
  push:
    paths:
      - "terraform/captionhealth.com/**"
  workflow_dispatch:

jobs:
  find-subfolders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find second-level subfolders
        id: find-subfolders
        run: |
          # Change to the target directory
          cd terraform/captionhealth.com

          # Find second-level subdirectories
          SUBFOLDERS=$(find . -mindepth 2 -maxdepth 2 -type d | tr '\n' ' ')

          # Save the subfolders to an output variable
          echo "::set-output name=subfolders::$SUBFOLDERS"

  create-myfile:
    needs: find-subfolders
    uses: ./.github/workflows/create_myfile_job.yml
    with:
      directories: ${{ jobs.find-subfolders.outputs.subfolders }}
