name: Create myfile.txt in each second-level subfolder

on:
  push:
    # paths:
    # - "terraform/captionhealth.com/**"
  workflow_dispatch:

jobs:
  find-subfolders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find second-level subfolders
        id: find_subfolders
        shell: bash
        env:
          ROOT_DIR: "./terraform/captionhealth.com/dev1"
        run: chmod +x ./.github/scripts/find_subfolders.sh
          ./.github/scripts/find_subfolders.sh

      - name: Print JSON
        run: echo ${{ fromJson(steps.find_subfolders.outputs.subfolders) }}

      # - name: Find second-level subfolders
      #   id: find_subfolders
      #   run: |
      #     # Change to the target directory
      #     cd terraform/captionhealth.com

      #     # Find second-level subdirectories and create a comma-separated list with spaces
      #     SUBFOLDERS=$(find . -mindepth 2 -maxdepth 2 -type d -exec realpath {} \; | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')

      #     # Format the result as a JSON array
      #     SUBFOLDERS_JSON=$(echo $SUBFOLDERS | jq -R 'split(", ")')

      #     # Save the subfolders to an environment file
      #     echo "SUBFOLDERS=$(jq -n --argjson arr "$SUBFOLDERS_JSON" '{"SUBFOLDERS": $arr}')" >> $GITHUB_ENV

      #     # Echo for troubleshooting
      #     echo $SUBFOLDERS
      #     echo $SUBFOLDERS_JSON

    outputs:
      subfolders: ${{ steps.find_subfolders.outputs.SUBFOLDERS }}

  create-myfile:
    needs: find-subfolders
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: ${{ fromJson(needs.find-subfolders.outputs.subfolders) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create myfile.txt
        uses: ./.github/actions/create-myfile
        with:
          directory: ${{ matrix.directory }}
