name: Create myfile.txt Job
on:
  workflow_call:
    inputs:
      directories:
        description: "List of directories to create myfile.txt in"
        required: true
        type: string

jobs:
  create-myfile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directories: ${{ fromJson(needs.find-subfolders.outputs.SUBFOLDERS) }}

    steps:
      - name: Create myfile.txt in each directory
        run: |
          for DIR in ${{ inputs.directories }}; do
            echo "Creating myfile.txt in $DIR"
            touch "$DIR/myfile.txt"
          done
        shell: bash
