name: Create myfile.txt in each second-level subfolder

on:
  push:
    # paths:
      # - "terraform/captionhealth.com/**"
  workflow_dispatch:

jobs:
  find-subfolders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find second-level subfolders
        id: find_subfolders
        run: |
          # Change to the target directory
          cd terraform/captionhealth.com

          # Find second-level subdirectories and create a comma-separated list with spaces
          SUBFOLDERS=$(find . -mindepth 2 -maxdepth 2 -type d | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')

          # Format the result as a JSON array
          SUBFOLDERS_JSON=$(echo "[\"${SUBFOLDERS//, /\", \"}\"]")

          # Save the subfolders to an environment file
          echo "SUBFOLDERS=$SUBFOLDERS_JSON" >> $GITHUB_ENV

  create-myfile:
    needs: find-subfolders
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: ${{ fromJson(env.SUBFOLDERS) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create myfile.txt
        uses: ./.github/actions/create-myfile
        with:
          directory: ${{ matrix.directory }}
