name: Create myfile.txt in each second-level subfolder

on:
  push:
    # paths:
    # - "terraform/captionhealth.com/**"
  workflow_dispatch:

jobs:
  find-subfolders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find second-level subfolders
        id: find_subfolders
        env:
          ROOT_DIR: "./terraform/captionhealth.com/dev1"
        # run: chmod +x ./.github/scripts/find_subfolders.sh
        #   ./.github/scripts/find_subfolders.sh
        run: |
          # Define the root directory
          root_dir=$ROOT_DIR

          # Initialize an empty JSON object
          json_output="{ \"SUBFOLDERS\": {} }"

          # Loop through subfolders
          for subfolder in "$root_dir"/*; do
              if [ -d "$subfolder" ]; then
                  # Extract subfolder name
                  subfolder_name=$(basename "$subfolder")

                  # Get absolute path
                  absolute_path=$(realpath "$subfolder")

                  # Add subfolder name and absolute path to JSON
                  json_output=$(echo "$json_output" | jq --arg name "$subfolder_name" --arg path "$absolute_path" '.SUBFOLDERS += { ($name): $path }')
              fi
          done

          # Set the JSON output as an environment variable
          # echo "SUBFOLDERS=$json_output" >> $GITHUB_ENV
          echo "testenv="Hello Avan" >> $GITHUB_ENV

      - name: Print JSON
        run: |
          echo "Hello World!"
          echo ${{ env.SUBFOLDERS }}
          echo ${{ steps.find_subfolders.outputs.SUBFOLDERS }}
          echo ${{ env.testenv }}
          echo ${{ steps.find_subfolders.outputs.testenv }}

      # - name: Find second-level subfolders
      #   id: find_subfolders
      #   run: |
      #     # Change to the target directory
      #     cd terraform/captionhealth.com

      #     # Find second-level subdirectories and create a comma-separated list with spaces
      #     SUBFOLDERS=$(find . -mindepth 2 -maxdepth 2 -type d -exec realpath {} \; | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')

      #     # Format the result as a JSON array
      #     SUBFOLDERS_JSON=$(echo $SUBFOLDERS | jq -R 'split(", ")')

      #     # Save the subfolders to an environment file
      #     echo "SUBFOLDERS=$(jq -n --argjson arr "$SUBFOLDERS_JSON" '{"SUBFOLDERS": $arr}')" >> $GITHUB_ENV

      #     # Echo for troubleshooting
      #     echo $SUBFOLDERS
      #     echo $SUBFOLDERS_JSON

    outputs:
      subfolders: ${{ steps.find_subfolders.outputs.SUBFOLDERS }}

  create-myfile:
    needs: find-subfolders
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: ${{ fromJson(needs.find-subfolders.outputs.subfolders) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create myfile.txt
        uses: ./.github/actions/create-myfile
        with:
          directory: ${{ matrix.directory }}
