name: Env tests
on: push

env:
  FOO_ROOT: bar on root

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FOO_JOB: bar on job
    steps:
      - uses: actions/checkout@v1
      - name: Test envs
        run: |
          chmod +x ./.github/scripts/env-test.sh
          ./.github/scripts/env-test.sh
        env:
          FOO_STEP: bar on step